### ISSUE TITLE
crate2nix attempts to build binaries without their target-specific required-features

### ISSUE THREAD

**Issue by JJJollyjim** [kolloch/crate2nix#129]
For example, try generating and building https://github.com/aahancoc/tree_magic/tarball/0.2.3

The binary fails to build since it can't find `clap`. Here's the relevant Cargo.toml snippet:

```toml
[features]
cli = ["clap", "tabwriter", "scoped_threadpool", "walkdir", "num_cpus"]
# ...
default = []

[lib]
crate-type = ["lib"]
path = "src/lib.rs"

[[bin]]
required-features = ["cli"]
name = "tmagic"
path = "src/main.rs"
```

Thanks :)

And here's the diffedDefaultPackageFeatures:

```json
{
  "differentFeatures": {},
  "onlyInCargo": [
    "ansi_term",
    "atty",
    "bitflags",
    "clap",
    "cloudabi",
    "hermit-abi",
    "num_cpus",
    "redox_syscall",
    "same-file",
    "scoped_threadpool",
    "strsim",
    "tabwriter",
    "textwrap",
    "unicode-width",
    "vec_map",
    "walkdir",
    "winapi",
    "winapi-i686-pc-windows-gnu",
    "winapi-util",
    "winapi-x86_64-pc-windows-gnu"
  ],
  "onlyInCrate2Nix": []
}
```
