### ISSUE TITLE
Renames outside of `[dependencies]` sections aren't tagged as such

### ISSUE THREAD

**Issue by Fuuzetsu** [kolloch/crate2nix#223]
If you have something like
```toml
[package]
name = "repro"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
renamed_itoa = { version = "0.4.8", features = ["i128"], package = "itoa" }
```

crate2nix does not generate a renamed package, it instead generates something like
```nix
{
            name = "itoa";
            packageId = "itoa 0.4.8";
            features = [ "i128" ];
}
```

It does the right thing if the dependency is moved to `[dependencies]`

```nix
          {
            name = "itoa";
            packageId = "itoa 0.4.8";
            rename = "renamed_itoa";
            features = [ "i128" ];
          }
```

It seems like this is intended to work as I see this:

```nix
dependenciesWithRenames =
              lib.filter (d: d ? "rename")
                (
                  filterEnabledDependenciesForThis
                    (
                      (crateConfig.buildDependencies or [ ])
                      ++ (crateConfig.dependencies or [ ])
                      ++ devDependencies
                    )
                );
```

Maybe somewhere in crate2nix the rename code forgot to be plugged in for `dev-dependencies` and `build-dependencies`?

This is a problem if we have overlapping but renamed packages outside of `dependencies`.
