### ISSUE TITLE
dbus_codegen: extern location for dbus_codegen does not exist

### ISSUE THREAD

**Issue by evanjs** [kolloch/crate2nix#53]
As mentioned in https://github.com/kolloch/crate2nix/issues/51#issuecomment-557947691:

When attempting to import `dbus_codegen`, I get some strange errors.

Here is a minimal reproducible example for this issue
``` toml
# Cargo.toml

[package]
name = "hello-from-generated-code"
version = "0.1.0"
authors = ["you@example.com"]
build = "src/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
dbus = { git = "https://github.com/diwic/dbus-rs/" }

[build-dependencies]
dbus-codegen = { git = "https://github.com/diwic/dbus-rs/" }
```
``` rust
// src/build.rs
use std::env;
use std::fs::File;
use std::io::Write;
use std::path::Path;

use dbus_codegen;

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("hello.rs");
    let mut f = File::create(&dest_path).unwrap();

    f.write_all(
        b"
        pub fn message() -> &'static str {
            \"Hello, World!\"
        }
    ",
    )
    .unwrap();
}
```

``` rust
// src/main.rs

include!(concat!(env!("OUT_DIR"), "/build.rs"));

fn main() {
    println!("{}", message());
}
```

This is basically the same source that is presented on https://doc.rust-lang.org/cargo/reference/build-scripts.html#case-study-code-generation, with the addition of `use dbus_codegen;` to `build.rs`.

Here is the sort of error message I am getting:
```
rust_crate2nix> unpacking sources
rust_crate2nix> unpacking source archive /nix/store/l9clysw4na0mb84i9525cyrhg2ams3yn-crate2nix-51rust_crate2nix> source root is crate2nix-51rust_crate2nix> patching sources
rust_crate2nix> configuring
rust_crate2nix> Building src/build.rs (crate2nix-51)
rust_crate2nix> Running rustc --crate-name build_script_build src/build.rs --crate-type bin -C opt-level=3 -C codegen-units=8 --edition 2018 --cfg feature="default" --out-dir target/build/crate2nix-51 --emit=dep-info,link -L dependency=target/buildDeps --extern dbus_codegen=/nix/store/w89xkakvva5mz8zmp85v35hvdl0l3jq1-rust_dbus-codegen-0.4.1/lib/libdbus_codegen-6c8a034000.rlib --cap-lints allow --color always
rust_crate2nix> error: extern location for dbus_codegen does not exist: /nix/store/w89xkakvva5mz8zmp85v35hvdl0l3jq1-rust_dbus-codegen-0.4.1/lib/libdbus_codegen-6c8a034000.rlib
rust_crate2nix> error[E0463]: can't find crate for `dbus_codegen`
rust_crate2nix>  --> src/build.rs:3:5
rust_crate2nix>   |
rust_crate2nix> 3 | use dbus_codegen;rust_crate2nix>   |     ^^^^^^^^^^^^ can't find craterust_crate2nix> error: aborting due to 2 previous errors
rust_crate2nix> For more information about this error, try `rustc --explain E0463`.
builder for '/nix/store/7izm2fi5xvlspv73srvsnanm8iksf9ss-rust_crate2nix-51-0.1.0.drv' failed with exit code 1; last 10 log lines:
  
  error[E0463]: can't find crate for `dbus_codegen`
   --> src/build.rs:3:5
    |
  3 | use dbus_codegen;
    |     ^^^^^^^^^^^^ can't find crate
  
  error: aborting due to 2 previous errors
  
  For more information about this error, try `rustc --explain E0463`.
[0 built (1 failed)]
error: build of '/nix/store/7izm2fi5xvlspv73srvsnanm8iksf9ss-rust_crate2nix-51-0.1.0.drv' failed
```

This error seems to be slightly different from that mentioned in https://github.com/kolloch/crate2nix/issues/51#issuecomment-557947691.
