### ISSUE TITLE
Super-linear instantiation counts/time

### ISSUE THREAD

**Issue by nagisa** [kolloch/crate2nix#90]
We have a fairly large workspace which in total pulls in approximately 900 dependencies IIRC. Running `nix-instantiate Cargo.nix` for that workspace takes minutes. Taking a look into it I found that it instantiates some crate derivations multiple times, sometimes tens of thousands of times!

```
   4503 instantiated 'rust_syn-1.0.14' -> '/nix/store/gw8q7d7sjk1m0h4i4flnmhfi0bc8pifa-rust_syn-1.0.14.drv'
   4799 instantiated 'rust_getrandom-0.1.14' -> '/nix/store/qi0zq2iib6j40hfafbrkj9zzfymlb186-rust_getrandom-0.1.14.drv'
   8374 instantiated 'rust_num-traits-0.2.11' -> '/nix/store/rir6x3zwh1r0gz0b8mpr5zmnjiqyx0z2-rust_num-traits-0.2.11.drv'
   8709 instantiated 'rust_cfg-if-0.1.10' -> '/nix/store/48bsy1kawm8k5sl0cj82cyr5ypfasjrx-rust_cfg-if-0.1.10.drv'
   9035 instantiated 'rust_libc-0.2.66' -> '/nix/store/56lnlnalmrfq3k7pzrjw543pidw6c2l2-rust_libc-0.2.66.drv'
  12914 instantiated 'rust_quote-1.0.2' -> '/nix/store/qw2k8q740mp7zv2xnbwqch1vhcz7b649-rust_quote-1.0.2.drv'
  14090 instantiated 'rust_autocfg-1.0.0' -> '/nix/store/flq0p6kpm4g6fvbxhpvkdiqcxqwyjhn7-rust_autocfg-1.0.0.drv'
  25809 instantiated 'rust_proc-macro2-1.0.8' -> '/nix/store/d00pj6n278m8ks6n6qykimxdd2gjdllc-rust_proc-macro2-1.0.8.drv'
  32272 instantiated 'rust_unicode-xid-0.2.0' -> '/nix/store/cb8abh74a2hnxjp7120c75hka3s2dxr4-rust_unicode-xid-0.2.0.drv
```

This issue can also be reproduced with smaller workspaces too! While it won’t take minutes to instantiate, you will still notice it being slow. 

### Reproducer 

First, copy the following `Cargo.toml` file to somewhere: 

```toml
[package]
name = "x"
version = "0.1.0"

[dependencies]
serde = { version = "1", features = ["derive"] }
failure = "0.1"
thiserror = "1"
structopt = "0.3"
derive_more = "0.99"
num-derive = "0.3"
html5ever = "0.25"
log = "0.4"
rand_core = "0.5"
serde_json = "1"
time = "0.2"
url = "2"
semver = "0.9"
toml = "0.5"
chrono = "0.4"
hyper = "0.13"
hyper-rustls = "0.19"
hyper-openssl = "0.8"
prometheus = "0.7"
yup-oauth2 = "4"
tonic = "0.1"
pyo3 = "0.8"
numpy = "0.7"
peroxide = "0.19.4"
```

Then run

```bash
# bash
cargo update
crate2nix generate
time nix-instantiate Cargo.nix -vvv 2>&1 >/dev/null | grep instantiated | sort | uniq -c | sort -h | tail -n 10
```

You should see something resembling the following output:

```
     78 instantiated 'rust_lazy_static-1.4.0' -> '/nix/store/jydym8n46zd7nyfb6hcyjl2lgsdlkkbk-rust_lazy_static-1.4.0.drv'
     80 instantiated 'rust_log-0.4.8' -> '/nix/store/bbc8vk9zb51rwjf3rd8n9337axgs27s1-rust_log-0.4.8.drv'
     90 instantiated 'rust_bytes-0.5.4' -> '/nix/store/pnxs5gg6vani6nvrksgdva9903qii88i-rust_bytes-0.5.4.drv'
     99 instantiated 'rust_slab-0.4.2' -> '/nix/store/7qm8gpyfil2pp2mar8x8ihyz2i8346q3-rust_slab-0.4.2.drv'
    175 instantiated 'rust_syn-1.0.14' -> '/nix/store/4wsyaj2bngw52jdy4fmz1s2x13g1iyqs-rust_syn-1.0.14.drv'
    190 instantiated 'rust_cfg-if-0.1.10' -> '/nix/store/4811bzvc8zidig9gnpf8ddq48mn0hwi9-rust_cfg-if-0.1.10.drv'
    270 instantiated 'rust_libc-0.2.66' -> '/nix/store/2ss6n4yqpgx7m13d4ry073fdqw6yxwb3-rust_libc-0.2.66.drv'
    351 instantiated 'rust_quote-1.0.2' -> '/nix/store/z9ifpss40fslb6db0w7hm4b1i83n4l4n-rust_quote-1.0.2.drv'
    696 instantiated 'rust_proc-macro2-1.0.8' -> '/nix/store/5zdy41ix0h0ygqh8f14wx97wd1fky4az-rust_proc-macro2-1.0.8.drv'
    872 instantiated 'rust_unicode-xid-0.2.0' -> '/nix/store/669nxgb9zzw5kvlprh3r0fnfqiga5sy0-rust_unicode-xid-0.2.0.drv'

real	0m3.121s
user	0m2.633s
sys	0m0.239s
```

---

I have no idea where to even begin looking or what could cause nix to re-instantiate the same crate many many times. It could be an issue inherent to nix, but as I’m not sure whether it is, I’ve reported it here first.

cc @andir
